"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { loginSchema, registerSchema } from "@hirematch/validation";
import { z } from "zod";
import { LoaderCircle } from "lucide-react";

type LoginValues = z.infer<typeof loginSchema>; type RegisterValues = z.infer<typeof registerSchema>;
export function AuthForm({ mode }: { mode: "login" | "register" }) {
  const schema = mode === "login" ? loginSchema : registerSchema; const [serverError, setServerError] = useState(""); const [complete, setComplete] = useState(false);
  const form = useForm<LoginValues & Partial<RegisterValues>>({ resolver: zodResolver(schema), defaultValues: { name: "", email: "", password: "", role: "CANDIDATE" } });
  async function submit(values: LoginValues & Partial<RegisterValues>) { setServerError(""); try { const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4000/api/v1"}/auth/${mode}`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const body = await response.json() as { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "Something went wrong."); setComplete(true); } catch (error) { setServerError(error instanceof Error ? error.message : "Something went wrong."); } }
  if (complete) return <div className="rounded-2xl bg-mint p-6"><p className="font-bold">{mode === "login" ? "You’re signed in." : "Your account is ready."}</p><p className="mt-1 text-sm text-ink/65">Continue to your dashboard to start matching.</p><a className="mt-4 inline-block rounded-xl bg-ink px-4 py-2 text-sm font-bold text-white" href="/candidate/dashboard">Open dashboard</a></div>;
  return <form className="space-y-4" onSubmit={form.handleSubmit(submit)} noValidate>{mode === "register" && <><label className="block"><span className="mb-1.5 block text-sm font-semibold">Full name</span><input className="input" {...form.register("name")} autoComplete="name"/></label>{form.formState.errors.name && <p className="text-sm text-red-700">{form.formState.errors.name.message}</p>}<fieldset><legend className="mb-2 text-sm font-semibold">I’m here to</legend><div className="grid grid-cols-2 gap-2"><label className="rounded-xl border border-ink/15 p-3 text-sm"><input type="radio" value="CANDIDATE" {...form.register("role")} className="mr-2"/>Find work</label><label className="rounded-xl border border-ink/15 p-3 text-sm"><input type="radio" value="RECRUITER" {...form.register("role")} className="mr-2"/>Hire talent</label></div></fieldset></>}<label className="block"><span className="mb-1.5 block text-sm font-semibold">Email</span><input className="input" type="email" {...form.register("email")} autoComplete="email"/></label>{form.formState.errors.email && <p className="text-sm text-red-700">{form.formState.errors.email.message}</p>}<label className="block"><span className="mb-1.5 block text-sm font-semibold">Password</span><input className="input" type="password" {...form.register("password")} autoComplete={mode === "login" ? "current-password" : "new-password"}/></label>{form.formState.errors.password && <p className="text-sm text-red-700">{form.formState.errors.password.message}</p>}{serverError && <div role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-800">{serverError}</div>}<button disabled={form.formState.isSubmitting} className="focus-ring flex w-full justify-center rounded-xl bg-ink px-4 py-3 font-bold text-white hover:bg-forest disabled:opacity-50">{form.formState.isSubmitting ? <LoaderCircle className="animate-spin"/> : mode === "login" ? "Log in" : "Create account"}</button></form>;
}
