import Link from "next/link";
import { Bell, BriefcaseBusiness, Building2, ChartNoAxesCombined, ChevronDown, FileText, Gauge, Heart, Search, Settings, Shield, Users } from "lucide-react";
import { Logo } from "./logo";

const nav = {
  candidate: [["dashboard","Overview",Gauge],["recommended","Recommended",Search],["applications","Applications",BriefcaseBusiness],["saved","Saved jobs",Heart],["resume","Resume",FileText],["notifications","Notifications",Bell],["settings","Settings",Settings]],
  recruiter: [["dashboard","Overview",Gauge],["company","Company",Building2],["jobs","Jobs",BriefcaseBusiness],["applicants","Applicants",Users],["create-job","Create job",FileText],["analytics","Analytics",ChartNoAxesCombined],["settings","Settings",Settings]],
  admin: [["dashboard","Overview",Gauge],["users","Users",Users],["companies","Companies",Building2],["jobs","Jobs",BriefcaseBusiness],["reports","Reports",ChartNoAxesCombined],["audit-logs","Audit logs",Shield],["settings","Settings",Settings]]
} as const;

export function DashboardShell({ role, current, children }: { role: keyof typeof nav; current: string; children: React.ReactNode }) {
  return <div className="min-h-screen bg-paper"><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-ink/10 bg-white p-5 lg:flex lg:flex-col"><Logo/><nav className="mt-10 flex-1 space-y-1">{nav[role].map(([path,label,Icon]) => <Link key={path} href={`/${role}/${path}`} className={`focus-ring flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold ${current === path ? "bg-ink text-white" : "text-ink/60 hover:bg-paper hover:text-ink"}`}><Icon size={18}/>{label}</Link>)}</nav><div className="rounded-2xl bg-mint p-4"><p className="text-xs font-bold uppercase tracking-wider text-forest">{role} workspace</p><p className="mt-1 text-sm">Portfolio demo account</p></div></aside><div className="lg:pl-64"><header className="sticky top-0 z-20 flex h-18 items-center justify-between border-b border-ink/10 bg-paper/90 px-5 py-4 backdrop-blur lg:px-9"><div className="lg:hidden"><Logo/></div><p className="hidden text-sm text-ink/50 lg:block">Friday, October 2</p><div className="flex items-center gap-3"><button className="focus-ring relative rounded-xl border border-ink/10 bg-white p-2.5" aria-label="Notifications"><Bell size={18}/><span className="absolute right-1.5 top-1.5 size-2 rounded-full bg-forest"/></button><button className="focus-ring flex items-center gap-2 rounded-xl border border-ink/10 bg-white px-3 py-2 text-sm font-bold"><span className="grid size-7 place-items-center rounded-lg bg-lime">AR</span><span className="hidden sm:inline">Alex Rivera</span><ChevronDown size={14}/></button></div></header><main className="mx-auto max-w-7xl p-5 lg:p-9">{children}</main></div></div>;
}
